### ISSUE TITLE
S3 Could not connect to the endpoint URL

### ISSUE THREAD

**Issue by arkkanoid** [deis/postgres#110]
Trying to configure Deis-rc1 with S3, the database fails on start.

The Object Storage configuration is set in the eu-west-1 region.
I can connect with boto3 in the same bucket with the same credentials succesfully.  
I've the same configuration in Deis-beta2 and it still works.

```
/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/002_create_bucket.sh
Traceback (most recent call last):
  File "/bin/create_bucket", line 22, in <module>
    conn.meta.client.head_bucket(Bucket=bucket_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 537, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 146, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 274, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 314, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 356, in _check_caught_exception
    raise caught_exception
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://XXXXXXXXXX.s3.amazonaws.com/"  
```

**Comment by bacongobbler** [comment]
would you please share the credentials you placed in `generate_params.toml`, masking your access and secret key?

`cat ~/.helmc/workspace/charts/workflow-rc1/tpl/generate_params.toml`

**Comment by arkkanoid** [comment]
```
storage = "s3"

[s3]
accesskey = "xxxxxxx"
secretkey = "XXXXXXXXXXXXXXXXXXX"
# Any S3 region
region = "eu-west-1"
# Your buckets.
registry_bucket = "omk-k8sdeisv2-registry"
database_bucket = "omk-k8sdeisv2-database"
builder_bucket = "omk-k8sdeisv2-storage"
```

Could be a problem related with the AWS region?

**Comment by bacongobbler** [comment]
quite likely.

**Comment by arkkanoid** [comment]
My fault. I'd a wrong configuration in my Kubernetes cluster.
Thanks
