### ISSUE TITLE
Error messages on pushing WAL to Azure blob.

### ISSUE THREAD

**Issue by monaka** [deis/postgres#119]
The deis-database instance in my cluster logs like below.
I use Azure blob and the node instance is Standard A3.
K8s master and Etcds are located in another instances.
There is no additional application.
So I think the spec is enough.

I got response by calling `curl http://monadeis2.blob.core.windows.net/` in the pod
So network is reachable.

Even though I got error messages, it seems uploads are done with success...
I can see the blobs on Azure Portal. 
![screenshot 2016-06-20 at 14 53 22](https://cloud.githubusercontent.com/assets/101795/16184383/e1eaa3de-36f6-11e6-9423-3bce02d4a267.png)

```
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-push".
        STRUCTURED: time=2016-06-20T05:40:49.645955-00 pid=406
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/000000010000000000000001" to "wabs://database/wal_005/000000010000000000000001.lzo".
        STRUCTURED: time=2016-06-20T05:40:49.753617-00 pid=406 action=push-wal key=wabs://database/wal_005/000000010000000000000001.lzo prefix= seg=000000010000000000000001 state=begin
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/000000010000000000000002" to "wabs://database/wal_005/000000010000000000000002.lzo".
        STRUCTURED: time=2016-06-20T05:40:50.053689-00 pid=406 action=push-wal key=wabs://database/wal_005/000000010000000000000002.lzo prefix= seg=000000010000000000000002 state=begin
requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): monadeis2.blob.core.windows.net
requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): monadeis2.blob.core.windows.net
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 609, in main
            concurrency=args.pool_size)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 285, in wal_archive
            group.join()
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/pg/wal_transfer.py", line 135, in join
            val = self.wait_change.get()
          File "/usr/local/lib/python2.7/dist-packages/gevent/queue.py", line 571, in get
            return waiter.get()
          File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 875, in get
            return self.hub.switch()
          File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 606, in switch
            return greenlet.switch(self)
        LoopExit: ('This operation would block forever', <Hub at 0x7f92d9cb9af0 epoll default pending=0 ref=0 fileno=9>)

        STRUCTURED: time=2016-06-20T05:40:51.188561-00 pid=406
LOG:  archive command failed with exit code 2
DETAIL:  The failed archive command was: envdir "/etc/wal-e.d/env" wal-e wal-push pg_xlog/000000010000000000000001
WARNING:  archiving transaction log file "000000010000000000000001" failed too many times, will try again later
```

```
$ kubectl get pods --namespace=deis   
NAME                          READY     STATUS    RESTARTS   AGE
deis-database-48zts           1/1       Running   0          1m
```

**Comment by monaka** [comment]
Storage account (Standard-LRS) and VMs are placed in the same zone.

**Comment by monaka** [comment]
I reviewed code in WAL-E and tried to apply some hacks.
Their current code may be not stable.
(Generally, asynchronous I/O is difficult as you know.)
It might be better to use previous versions.

**Comment by bacongobbler** [comment]
We use [a fork of wal-e for Workflow](https://github.com/deis/postgres/blob/ebd3e1c0f8d7a2580d5c097a924ae3a55553f772/rootfs/Dockerfile#L48). You might want to try that first before submitting tickets upstream.

**Comment by monaka** [comment]
I see Deis uses forked version.
But regards with my revier, this issue isn't caused by patches.
I'll try patched version also. And also I informed to upstream to same time.

**Comment by monaka** [comment]
I close this issue as I move this issue.
