### ISSUE TITLE
Bucket isn't recreated if minio restarts

### ISSUE THREAD

**Issue by mboersma** [deis/postgres#86]
If minio is restarted, errors appear in both the minio logs:

```
time="2016-04-12T20:39:32Z" level=error msg="CreateObject failed." Error={Bucket not found: dbwal fs.BucketNotFound [{224 pkg/fs/fs-object.go fs.Filesystem.CreateObject map[]} {466 object-handlers.go main.storageAPI.PutObjectHandler map[]}] map[host.os:linux host.name:deis-minio-44vrs mem.used:1.9MB mem.total:8.8MB mem.heap.used:1.9MB mem.heap.total:5.7MB host.arch:amd64 host.lang:go1.6 host.cpus:2]}
```

and in database:

``` python
wal_e.blobstore.s3.calling_format INFO     MSG: connecting to S3 with WALE_S3_ENDPOINT (http://10.100.66.122:9000)
        STRUCTURED: time=2016-04-12T21:14:56.937523-00 pid=904
boto3.resources.action INFO     Calling s3:put_object with {'Body': <open file '<fdopen>', mode 'r+b' at 0x7f358b928c90>, u'Bucket': 'dbwal', 'Key': 'wal_005/000000010000000000000008.lzo'}
botocore.vendored.requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): 10.100.66.122
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload.py", line 48, in __call__
    self.gpg_key_id)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
    k = blobstore.uri_put_file(creds, url, tf)
  File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/s3/s3_util.py", line 50, in uri_put_file
    k = bucket.put_object(Key=url_tup.path.lstrip('/'), Body=fp)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 498, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 236, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 500, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist.
<Greenlet at 0x7f358b92b9b0: <wal_e.worker.upload.WalUploader object at 0x7f358b8f2ad0>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with ClientError

wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 609, in main
            concurrency=args.pool_size)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 285, in wal_archive
            group.join()
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/pg/wal_transfer.py", line 144, in join
            raise val
        ClientError: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist.

        STRUCTURED: time=2016-04-12T21:14:56.961924-00 pid=904
LOG:  archive command failed with exit code 2
DETAIL:  The failed archive command was: envdir "/etc/wal-e.d/env" wal-e wal-push pg_xlog/000000010000000000000007
WARNING:  archiving transaction log file "000000010000000000000007" failed too many times, will try again later
```

Ideally the wal-e script could handle this by recreating the bucket as needed. Storage may be lost but these particular errors could be avoided.

**Comment by bacongobbler** [comment]
once minio is deleted, all data is lost, including previous WAL logs shipped. There's no way to tell wal-e to re-push all lost data in that bucket once it's been deleted. Perhaps at this point it's best to document to restart the database so the bucket is re-created and a new base backup is created?

**Comment by bacongobbler** [comment]
closing as intentional
